### ISSUE TITLE
Figure out passwords without submitting to github.

### ISSUE THREAD

**Issue by toolgirl** [willfulbard/camphoric#10]
Currently in settings.py the password is empty, but in production we need to set a password probably by pulling in a local file.

**Comment by willfulbard** [comment]
My recommendation:

https://github.com/joke2k/django-environ

**Comment by majormoses** [comment]
I think you should extend that to any secret and not just postgres, for [example](https://github.com/willfulbard/camphoric/blob/94ae195f930c8467b372c05dcf2ecd8e9d186967/server/camphoric_server/settings.py#L22-L23)

**Comment by willfulbard** [comment]
Very good point, and it looks like a friendly passer-by open up an issue in that regard:

https://github.com/willfulbard/camphoric/issues/12
