### ISSUE TITLE
Migrate Larkcamp FrontEnd into this repo

### ISSUE THREAD

**Issue by toolgirl** [willfulbard/camphoric#24]

**Comment by evinism** [comment]
Sent this as an email to y'all, but here it is in issue form:

1. We use the same domain for both fe and be (e.g. not doing the whole www.camphoric and api.camphoric split)
2. All routes that don't fall into currently established subdomains (e.g. admin/, api/, api-auth/, api-auth-token/) get served the static react bootstrapping page (the html page with all the js/css includes, etc...)
3. React handles all routing beyond that point, as should be well handled by client-side React routing libs.

I'm guessing this approach will be simple enough to allow easy dev of both fe/be of the project.

**Comment by brsaylor** [comment]
A single domain sounds good to me. I'm not sure I completely understand the rest - would this still let us serve static files besides the React bootstrap page, and have separate public registration and admin apps (not django-admin, but our custom thing when we get to that)?
