### ISSUE TITLE
Assess using pipenv?

### ISSUE THREAD

**Issue by evinism** [willfulbard/camphoric#25]
Hey, all! I'm curious if you'd all want to start using [pipenv](https://github.com/pypa/pipenv)? I'm a big fan and like the tooling associated with keeping my python env relatively nice and clean in general.

if that's too much for y'all, no worries! I can deal with handling my own python env.

**Comment by brsaylor** [comment]
I’ve been thinking about trying pipenv, poetry or similar to solve the issues of keeping direct and transitive deps separate, as well as prod and dev-only deps separate. Evin, have you tried poetry or pip-tools?

Ben

**Comment by evinism** [comment]
no i haven't tried either of those, sadly, but I'm very open to either! I divert to whatever you choose here.
